# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lizii.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.totalLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(220, 20, 281, 31))
        self.totalLabel.setObjectName("totalLabel")
        self.amountInput = QtWidgets.QLineEdit(self.centralwidget)
        self.amountInput.setGeometry(QtCore.QRect(60, 100, 113, 22))
        self.amountInput.setObjectName("amountInput")
        self.categoryBox = QtWidgets.QComboBox(self.centralwidget)
        self.categoryBox.setGeometry(QtCore.QRect(330, 100, 351, 22))
        self.categoryBox.setObjectName("categoryBox")
        self.categoryBox.addItem("")
        self.categoryBox.addItem("")
        self.categoryBox.addItem("")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(132, 230, 401, 28))
        self.addButton.setObjectName("addButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.totalLabel.setText(_translate("MainWindow", "ჯამური ხარჯი: 0 ₾"))
        self.amountInput.setText(_translate("MainWindow", "შეიყვანე თანხა"))
        self.categoryBox.setItemText(0, _translate("MainWindow", "საკვები"))
        self.categoryBox.setItemText(1, _translate("MainWindow", "ტრანსპორტი"))
        self.categoryBox.setItemText(2, _translate("MainWindow", "გართობა"))
        self.addButton.setText(_translate("MainWindow", "დამატება"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
